#!/usr/bin/env python3

import sys, random

output_file_path = "puzzle"
target_word_length = 7
minimum_word_length = 4
frequency_field = 1
minimum_pangram_frequency = 0.0
verbose = False

def report(message):
	sys.stderr.write(f"\x1B[G\x1B[K{message}")
	sys.stderr.flush()

dictionary_path = ''
show_usage = False
args = sys.argv[1:]
while len(args) > 0:
	arg = args.pop(0)
	if arg == "letters:":
		letters_spec = args.pop(0).split('-')
		if len(letters_spec) == 2:
			minimum_word_length = int(letters_spec[0])
			target_word_length = int(letters_spec[1])
		else:
			target_word_length = int(letters_spec[0])
	elif arg == "frequency-field:":
		frequency_field = int(args.pop(0));
	elif arg == "min-frequency:":
		minimum_pangram_frequency = float(args.pop(0))
	elif arg == "to:":
		output_file_path = args.pop(0)
	elif arg == "-v" or arg == "--verbose":
		verbose = True
	elif arg == "--help":
		show_usage = True
	else:
		dictionary_path = arg
if len(dictionary_path) == 0 or show_usage:
	print(f"Usage: {sys.argv[0]} <dictionary-file> [options...]")
	print(f"Options are:")
	print(f"  letters: <num-letters>")
	print(f'    How many letters in a word, either as a range (eg. "3-7"), or just the');
	print(f'    maximum number of letters (with the minimum word length defaulting');
	print(f'    to 4).')
	print(f"  frequency-field: <field-number>")
	print(f"    Which field (zero-based) in the words file has each word's frequency.")
	print(f"    Default: 1.")
	print(f"  min-frequency: <frequency>")
	print(f"    Pangram must have at least this frequency out of the total frequency.")
	print(f"    Between 0 and 1, usually very small (eg. 1e-8).  Default: 0.0")
	print(f"  to: <out-file>")
	print(f'    Output file.  Default: "puzzle".')
	print(f"  -v")
	print(f'    Verbose output.')
	sys.exit(1)


# We're going to linearly scan the dictionary file three times.  Once just to
# find out how many words (lines) it has, once to select a random word, and
# once to find all the words that match it.

# How many words?  And total frequency?
num_lines = 0
total_frequency = 0.0
with open(dictionary_path, "r") as dict_file:
	for line in dict_file:
		num_lines += 1
		fields = line.split()
		if len(fields) > frequency_field:
			total_frequency += float(fields[frequency_field])

# Pick a word.
pangram = ''
pangram_frequency = 0.0
while len(pangram) == 0:
	start_line = random.randint(0, num_lines - 1)
	cur_line = 0
	with open(dictionary_path, "r") as dict_file:
		for line in dict_file:
			if cur_line < start_line:
				cur_line += 1
				continue

			fields = line.split()
			word = fields[0].lower()
			if len(word) == target_word_length:
				pangram_frequency = 0.0
				if total_frequency > 0.0:
					pangram_frequency = float(fields[frequency_field]) / total_frequency
					if pangram_frequency < minimum_pangram_frequency:
						continue
				pangram = word
				break

# Pick a letter.
key_letter = pangram[random.randint(0, len(pangram) - 1)]

# Output the puzzle.
def pangram_contains(word):
	if key_letter not in word:
		return False
	letters_left = pangram
	for letter in word:
		index = letters_left.find(letter)
		if index < 0:
			return False
		letters_left = letters_left[0:index] + letters_left[index + 1:]
	return True
num_words = 0
with open(output_file_path, "w") as out_file:
	out_file.write(f"{pangram} {key_letter}\n")
	with open(dictionary_path, "r") as dict_file:
		for line in dict_file:
			fields = line.split()
			word = fields[0].lower()
			if len(word) < minimum_word_length:
				continue
			if not pangram_contains(word):
				continue
			if len(fields) > frequency_field:
				out_file.write(f"{word} {fields[frequency_field]}\n")
			else:
				out_file.write(f"{word}\n")
			num_words += 1
			if verbose:
				report(f"Found {num_words} words from {num_lines} total words...")

if verbose:
	sys.stderr.write('\n')
	sys.stderr.flush()
else:
	print(f"Found {num_words} words from {num_lines} total words.")
	

if pangram_frequency > 0.0:
	print(f"Chosen word has frequency {pangram_frequency}.")
	print(f"Total frequency was {total_frequency}.")

