#!/usr/bin/env python3

import sys

output_file_path = "seven-letter-words"
target_word_length = 7

def report(message):
	sys.stderr.write(f"\x1B[G\x1B[K{message}")
	sys.stderr.flush()

if len(sys.argv) < 2:
	print(f"Usage: {sys.argv[0]} <dictionary-file>")
	sys.exit(1)

dictionary_path = sys.argv[1]
num_words_found = 0
with open(output_file_path, "w") as out_file:
	with open(dictionary_path, "r") as dict_file:
		for word in dict_file:
			word = word.strip()
			if len(word) == target_word_length:
				out_file.write(f"{word}\n")
				num_words_found += 1
				report(f"Found {num_words_found} words...")

sys.stderr.write("\n")
sys.stderr.flush()


